name: 'Setup Conda'
description: 'Create conda environment for GitHub Action Job'

runs:
  using: "composite"
  steps:
    - name: Retrieve CryoCloud Conda-Lock File
      shell: bash -le {0}
      run: |
        cd conda
        wget https://github.com/CryoInTheCloud/hub-image/blob/9d2485c39e1033694eaefe597c9a0a414cc623b9/conda-linux-64.lock
  
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: conda/conda-linux-64.lock
        environment-name: hackweek
        cache-environment: true
        cache-downloads: true
